const DAY=86400000;
const initial={title:'Website launch',phases:[
 {id:'p1',name:'DISCOVERY & STRATEGY',collapsed:false,tasks:[{id:'t1',name:'Stakeholder interviews',start:'2026-07-06',end:'2026-07-10',progress:100,owner:'MK',color:'orange'},{id:'t2',name:'Market research',start:'2026-07-08',end:'2026-07-15',progress:80,owner:'AL',color:'blue',predecessor:'t1'},{id:'t3',name:'Product brief',start:'2026-07-14',end:'2026-07-20',progress:45,owner:'EA',color:'green',predecessor:'t2'}],milestones:[{id:'m1',name:'Brief approved',date:'2026-07-21',predecessor:'t3'}]},
 {id:'p2',name:'DESIGN & EXPERIENCE',collapsed:false,tasks:[{id:'t4',name:'Information architecture',start:'2026-07-22',end:'2026-07-29',progress:25,owner:'JD',color:'purple',predecessor:'m1'},{id:'t5',name:'Visual direction',start:'2026-07-24',end:'2026-08-04',progress:10,owner:'SN',color:'orange'},{id:'t6',name:'Prototype & validation',start:'2026-08-03',end:'2026-08-14',progress:0,owner:'MK',color:'blue',predecessor:'t5'}],milestones:[]},
 {id:'p3',name:'BUILD & LAUNCH',collapsed:false,tasks:[{id:'t7',name:'Development sprint',start:'2026-08-10',end:'2026-08-28',progress:0,owner:'AL',color:'green',predecessor:'t6'},{id:'t8',name:'QA & launch',start:'2026-08-27',end:'2026-09-04',progress:0,owner:'EA',color:'purple',predecessor:'t7'}],milestones:[{id:'m2',name:'Go live',date:'2026-09-04',predecessor:'t8'}]}
]};
let state=migrateState(JSON.parse(localStorage.getItem('arcplan-state')||'null')||initial);let zoom='week',currentView='timeline';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],parse=s=>new Date(s+'T00:00:00'),iso=d=>new Date(d).toISOString().slice(0,10),add=(d,n)=>new Date(d.getTime()+n*DAY),days=(a,b)=>Math.round((parse(b)-parse(a))/DAY)+1;
function normalizeTask(t){if(!Array.isArray(t.segments)||!t.segments.length)t.segments=[{id:t.id+'s1',start:t.start,end:t.end}];t.segments=t.segments.filter(s=>s.start&&s.end).sort((a,b)=>a.start.localeCompare(b.start)).map((s,i)=>({id:s.id||t.id+'s'+(i+1),start:s.start,end:s.end}));if(!t.segments.length)t.segments=[{id:t.id+'s1',start:t.start,end:t.end}];t.start=t.segments[0].start;t.end=t.segments.reduce((max,s)=>s.end>max?s.end:max,t.segments[0].end);return t}
function migrateState(data){data.style=data.style||'executive';data.calendar=data.calendar||{shadeWeekends:false,offDays:[]};data.calendar.offDays=Array.isArray(data.calendar.offDays)?data.calendar.offDays:[];data.phases=(data.phases||[]).map(p=>({...p,tasks:(p.tasks||[]).map(normalizeTask),milestones:p.milestones||[]}));return data}
function taskSegments(t){return normalizeTask(t).segments}
function taskWorkDays(t){return taskSegments(t).reduce((sum,s)=>sum+days(s.start,s.end),0)}
function dependencyPath(a,b){const sx=a.right-1,sy=a.y,ex=b.left+2,ey=b.y;if(Math.abs(ey-sy)<1)return`M ${sx} ${sy} H ${ex}`;const gap=ex-sx,bx=gap>28?sx+gap/2:sx+14,vd=ey>sy?1:-1,hd=ex>bx?1:-1,r=Math.min(5,Math.abs(bx-sx)/2,Math.abs(ey-sy)/2,Math.abs(ex-bx)/2);if(r<1)return`M ${sx} ${sy} H ${bx} V ${ey} H ${ex}`;return`M ${sx} ${sy} H ${bx-r} Q ${bx} ${sy} ${bx} ${sy+vd*r} V ${ey-vd*r} Q ${bx} ${ey} ${bx+hd*r} ${ey} H ${ex}`}
function offDayMarkup(r,px,height){const custom=new Map((state.calendar?.offDays||[]).map(d=>[d.date,d]));let out='';for(let i=0;i<r.total;i++){const date=add(r.min,i),key=iso(date),entry=custom.get(key),weekend=state.calendar?.shadeWeekends&&(date.getDay()===0||date.getDay()===6),label=String(entry?.label||'Weekend').replace(/"/g,'&quot;');if(entry||weekend)out+=`<span class="off-day-shade${entry?' custom':''}" style="left:${i*px}px;width:${Math.max(px,1)}px;height:${height}px" title="${label}"></span>`}return`<div class="off-days-layer">${out}</div>`}
const save=()=>{localStorage.setItem('arcplan-state',JSON.stringify(state));const e=$('#saveStatus');if(e)e.textContent='Saved automatically on this device'};const toast=msg=>{const e=$('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)};
function allTasks(){return state.phases.flatMap(p=>p.tasks)}
function allMilestones(){return state.phases.flatMap(p=>p.milestones)}
function allNodes(){return[...allTasks().map(n=>({...n,type:'Task'})),...allMilestones().map(n=>({...n,type:'Milestone'}))]}
function nodeName(id){return allNodes().find(n=>n.id===id)?.name||''}
function successorNames(id){return allNodes().filter(n=>n.predecessor===id).map(n=>n.name)}
function createsCycle(id,predecessor){const seen=new Set([id]);let next=predecessor;while(next){if(seen.has(next))return true;seen.add(next);next=allNodes().find(n=>n.id===next)?.predecessor||''}return false}
function range(){const ts=allTasks(),ms=state.phases.flatMap(p=>p.milestones),today=parse(iso(new Date()));const starts=[...ts.map(t=>parse(t.start)),...ms.map(m=>parse(m.date)),today],ends=[...ts.map(t=>parse(t.end)),...ms.map(m=>parse(m.date)),today];let min=starts.length?new Date(Math.min(...starts)):add(today,-7),max=ends.length?new Date(Math.max(...ends)):add(today,21);min=add(min,-7);max=add(max,10);return{min,max,total:Math.round((max-min)/DAY)+1}}
function applyStyle(){document.body.dataset.theme=state.style||'executive';if($('#styleSelect'))$('#styleSelect').value=state.style||'executive'}
function render(){applyStyle();renderMetrics();renderTasks();renderTimeline();renderBoard();renderList();save()}
function renderMetrics(){const ts=allTasks(),ms=state.phases.flatMap(p=>p.milestones),avg=ts.length?Math.round(ts.reduce((s,t)=>s+t.progress,0)/ts.length):0;$('#metrics').innerHTML=`<div class="metric"><strong>${ts.length}</strong><span>Tasks</span></div><div class="metric"><strong>${state.phases.length}</strong><span>Phases</span></div><div class="metric"><strong>${ms.length}</strong><span>Milestones</span></div><div class="metric"><strong>${avg}%</strong><span>Progress</span></div>`}
function renderTasks(){let n=0;$('#taskList').innerHTML=state.phases.map(p=>`<div class="phase-row"><button data-toggle="${p.id}">${p.collapsed?'›':'⌄'}</button><span>${p.name}</span><small>${p.tasks.length+p.milestones.length}</small><span class="phase-actions"><button data-phase-add="${p.id}" title="Add task">＋</button><button data-milestone-add="${p.id}" title="Add milestone">◆</button><button data-phase-edit="${p.id}" title="Edit phase">✎</button></span></div>${p.collapsed?'':p.tasks.map(t=>`<div class="task-row" data-edit="${t.id}"><span class="task-num">${String(++n).padStart(2,'0')}</span><div class="task-info"><strong>${t.name}</strong><small>${taskWorkDays(t)} active days${taskSegments(t).length>1?' · '+taskSegments(t).length+' periods':''} · ${t.progress}%${t.predecessor?' · linked':''}</small></div><span class="avatar">${t.owner||'—'}</span></div>`).join('')+p.milestones.map(m=>`<div class="task-row" data-milestone-edit="${m.id}"><span class="task-num">◆</span><div class="task-info"><strong>${m.name}</strong><small class="type-badge">Milestone · ${parse(m.date).toLocaleDateString('en',{month:'short',day:'numeric'})}</small></div></div>`).join('')}`).join('');
 $$('[data-toggle]').forEach(b=>b.onclick=()=>{const p=state.phases.find(x=>x.id===b.dataset.toggle);p.collapsed=!p.collapsed;render()});$$('[data-edit]').forEach(e=>e.onclick=()=>openTask(e.dataset.edit));$$('[data-phase-add]').forEach(e=>e.onclick=()=>openTask(null,e.dataset.phaseAdd));$$('[data-phase-edit]').forEach(e=>e.onclick=()=>openPhase(e.dataset.phaseEdit));$$('[data-milestone-add]').forEach(e=>e.onclick=()=>openMilestone(null,e.dataset.milestoneAdd));$$('[data-milestone-edit]').forEach(e=>e.onclick=()=>openMilestone(e.dataset.milestoneEdit))}
function colorValue(c){const palettes={executive:{orange:'#d8dde5',blue:'#cbd4df',green:'#d5ddd7',purple:'#dad6df',red:'#e3d5d7',teal:'#d2dfde'},minimal:{orange:'#eceef1',blue:'#e1e5e9',green:'#e7e9e6',purple:'#e9e7ec',red:'#eee2e3',teal:'#e1ebea'},ocean:{orange:'#cbe9ed',blue:'#c9dff4',green:'#c9ebe7',purple:'#d6ddf3',red:'#efd5dc',teal:'#c8e7e6'},forest:{orange:'#e3e8cc',blue:'#d0e4dc',green:'#cce5d2',purple:'#dfe2d6',red:'#ead5d1',teal:'#cde2dc'},sunset:{orange:'#f7d4c4',blue:'#efd0d6',green:'#f4dfb8',purple:'#e4cfdb',red:'#f0c9cb',teal:'#cde4e1'},plum:{orange:'#ead6e4',blue:'#dcd9ef',green:'#dce3d7',purple:'#dfd0e8',red:'#ebcfd7',teal:'#d1e3e2'}};return(palettes[state.style]||palettes.executive)[c]||'#cbd4df'}
function renderBoard(){const groups=[['Not started',t=>t.progress===0],['In progress',t=>t.progress>0&&t.progress<75],['Review',t=>t.progress>=75&&t.progress<100],['Complete',t=>t.progress===100]];$('#boardView').innerHTML=`<div class="board-grid">${groups.map(([name,fn])=>{const ts=allTasks().filter(fn);return`<section class="board-column"><div class="board-column-head">${name}<span>${ts.length}</span></div>${ts.map(t=>`<article class="board-card" data-board-task="${t.id}" style="--card-color:${colorValue(t.color)}"><strong>${t.name}</strong><small>${state.phases.find(p=>p.tasks.includes(t)).name} · ${t.owner||'—'}</small><small>${parse(t.start).toLocaleDateString('en',{month:'short',day:'numeric'})} - ${parse(t.end).toLocaleDateString('en',{month:'short',day:'numeric'})}</small><div class="progress-track"><div class="progress-fill" style="width:${t.progress}%"></div></div></article>`).join('')}</section>`}).join('')}</div>`;$$('[data-board-task]').forEach(e=>e.onclick=()=>openTask(e.dataset.boardTask))}
function renderList(){$('#listView').innerHTML=`<table class="project-table"><thead><tr><th>Task</th><th>Owner</th><th>Start</th><th>End</th><th>Predecessor</th><th>Progress / Successors</th></tr></thead><tbody>${state.phases.map(p=>`<tr class="phase-table-row"><td colspan="6">${p.name}</td></tr>${p.tasks.map(t=>`<tr data-list-task="${t.id}"><td><span class="color-dot" style="background:${colorValue(t.color)}"></span>${t.name}</td><td>${t.owner||'—'}</td><td>${parse(t.start).toLocaleDateString()}</td><td>${parse(t.end).toLocaleDateString()}</td><td>${nodeName(t.predecessor)||'—'}</td><td><div class="list-progress"><div class="progress-track"><div class="progress-fill" style="width:${t.progress}%;background:${colorValue(t.color)}"></div></div>${t.progress}% · ${successorNames(t.id).join(', ')||'no successors'}</div></td></tr>`).join('')}${p.milestones.map(m=>`<tr data-list-milestone="${m.id}"><td>◆ ${m.name}</td><td>Milestone</td><td>${parse(m.date).toLocaleDateString()}</td><td>${parse(m.date).toLocaleDateString()}</td><td>${nodeName(m.predecessor)||'—'}</td><td>${successorNames(m.id).join(', ')||'No successors'}</td></tr>`).join('')}`).join('')}</tbody></table>`;$$('[data-list-task]').forEach(e=>e.onclick=()=>openTask(e.dataset.listTask));$$('[data-list-milestone]').forEach(e=>e.onclick=()=>openMilestone(e.dataset.listMilestone))}
function weekNum(d){const x=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));x.setUTCDate(x.getUTCDate()+4-(x.getUTCDay()||7));const y=new Date(Date.UTC(x.getUTCFullYear(),0,1));return Math.ceil((((x-y)/DAY)+1)/7)}
function bindBarDragging(pxPerDay){$$('[data-bar]').forEach(bar=>{bar.onpointerdown=event=>{if(event.button!==undefined&&event.button!==0)return;event.preventDefault();const task=allTasks().find(t=>t.id===bar.dataset.bar),segment=task&&taskSegments(task)[+bar.dataset.segment||0];if(!task||!segment)return;const mode=event.target.dataset.resize||'move',startX=event.clientX,originalLeft=parseFloat(bar.style.left),originalWidth=parseFloat(bar.style.width),duration=days(segment.start,segment.end);let moved=false,lastDelta=0;bar.classList.add('drag-preview');bar.setPointerCapture?.(event.pointerId);const move=e=>{const dx=e.clientX-startX;if(Math.abs(dx)>3)moved=true;let delta=Math.round(dx/pxPerDay);if(mode==='start')delta=Math.min(delta,duration-1);if(mode==='end')delta=Math.max(delta,-(duration-1));lastDelta=delta;if(mode==='move')bar.style.left=originalLeft+delta*pxPerDay+'px';if(mode==='start'){bar.style.left=originalLeft+delta*pxPerDay+'px';bar.style.width=originalWidth-delta*pxPerDay+'px'}if(mode==='end')bar.style.width=originalWidth+delta*pxPerDay+'px'};const finish=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',finish);document.removeEventListener('pointercancel',finish);bar.classList.remove('drag-preview');if(!moved||lastDelta===0)return;if(mode==='move'){segment.start=iso(add(parse(segment.start),lastDelta));segment.end=iso(add(parse(segment.end),lastDelta))}else if(mode==='start')segment.start=iso(add(parse(segment.start),lastDelta));else segment.end=iso(add(parse(segment.end),lastDelta));normalizeTask(task);bar.dataset.justDragged='1';render();toast(mode==='move'?`Work period moved ${Math.abs(lastDelta)} day${Math.abs(lastDelta)===1?'':'s'}`:`Work period ${mode} date updated`);setTimeout(()=>delete bar.dataset.justDragged,80)};document.addEventListener('pointermove',move);document.addEventListener('pointerup',finish);document.addEventListener('pointercancel',finish)}})}
function bindMilestoneDragging(pxPerDay){$$('.milestone[data-milestone]').forEach(marker=>{marker.onpointerdown=event=>{if(event.button!==undefined&&event.button!==0)return;event.preventDefault();event.stopPropagation();const milestone=allMilestones().find(m=>m.id===marker.dataset.milestone);if(!milestone)return;const startX=event.clientX,originalLeft=parseFloat(marker.style.left);let moved=false,lastDelta=0;marker.classList.add('drag-preview');marker.setPointerCapture?.(event.pointerId);const move=e=>{const dx=e.clientX-startX;if(Math.abs(dx)>3)moved=true;lastDelta=Math.round(dx/pxPerDay);marker.style.left=originalLeft+lastDelta*pxPerDay+'px'};const finish=()=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',finish);document.removeEventListener('pointercancel',finish);marker.classList.remove('drag-preview');if(!moved||lastDelta===0)return;milestone.date=iso(add(parse(milestone.date),lastDelta));marker.dataset.justDragged='1';render();toast(`Milestone moved to ${parse(milestone.date).toLocaleDateString('en',{month:'short',day:'numeric'})}`)};document.addEventListener('pointermove',move);document.addEventListener('pointerup',finish);document.addEventListener('pointercancel',finish)}})}
function renderTimeline(){
 const r=range(),unit=zoom==='day'?1:zoom==='week'?7:30,col=zoom==='day'?46:zoom==='week'?92:125,px=col/unit,count=Math.ceil(r.total/unit);
 const head=Array.from({length:count},(_,i)=>{const d=add(r.min,i*unit),label=zoom==='day'?d.toLocaleDateString('en',{weekday:'short'}):zoom==='week'?'W'+weekNum(d):d.toLocaleDateString('en',{month:'short'}),sub=zoom==='month'?d.getFullYear():d.toLocaleDateString('en',{month:'short',day:'numeric'});return`<div class="time-cell" style="--col-w:${col}px"><span>${label}</span><strong>${sub}</strong></div>`}).join('');
 let body='',y=0,pos={},segmentPaths='';
 state.phases.forEach(p=>{body+='<div class="timeline-phase"></div>';y+=44;if(!p.collapsed){p.tasks.forEach(t=>{const segments=taskSegments(t),bars=segments.map((s,i)=>{const left=Math.round((parse(s.start)-r.min)/DAY)*px,width=days(s.start,s.end)*px;return{left,right:left+width,width,index:i}}),rowY=y+27;pos[t.id]={left:bars[0].left,right:bars[bars.length-1].right,y:rowY};for(let i=1;i<bars.length;i++)if(bars[i].left-bars[i-1].right>3)segmentPaths+=`<path class="segment-link" marker-end="url(#segmentArrow)" d="M ${bars[i-1].right} ${rowY} H ${bars[i].left+2}"/>`;body+=`<div class="timeline-row" style="--col-w:${col}px">${bars.map((b,i)=>`<div class="bar ${t.color}" data-bar="${t.id}" data-segment="${i}" style="left:${b.left}px;width:${b.width}px;--progress:${t.progress}%"><span class="resize-handle start" data-resize="start"></span><span class="bar-label">${i?`Continued`:t.name}</span><span class="resize-handle end" data-resize="end"></span></div>`).join('')}</div>`;y+=54});p.milestones.forEach(m=>{const center=Math.round((parse(m.date)-r.min)/DAY)*px;pos[m.id]={left:center-11,right:center+11,y:y+27};body+=`<div class="timeline-row milestone-row" style="--col-w:${col}px"><div class="milestone" data-milestone="${m.id}" style="left:${center-10}px"></div><span class="milestone-label" data-milestone-label="${m.id}" style="left:${center+16}px">${m.name}</span></div>`;y+=54})}});
 let paths='';allNodes().forEach(n=>{const a=pos[n.predecessor],b=pos[n.id];if(a&&b)paths+=`<path class="dependency-line" marker-end="url(#arrow)" d="${dependencyPath(a,b)}"/>`});
 const svg=`<svg class="dependency-layer" width="${count*col}" height="${y}"><defs><marker id="arrow" viewBox="0 0 10 10" refX="9.5" refY="5" markerWidth="5.5" markerHeight="5.5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#778399"/></marker><marker id="segmentArrow" viewBox="0 0 10 10" refX="9.5" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#9aa4b3"/></marker></defs>${segmentPaths}${paths}</svg>`,today=(parse(iso(new Date()))-r.min)/DAY*px;
 $('#todayBtn').textContent=`Today · ${new Date().toLocaleDateString('en',{month:'short',day:'numeric'})}`;$('#timeline').style.width=count*col+'px';$('#timeline').innerHTML=`<div class="time-header" style="--col-w:${col}px">${head}</div><div class="today-line" style="left:${today}px"></div>${body}${offDayMarkup(r,px,y)}${svg}`;bindBarDragging(px);bindMilestoneDragging(px);$$('[data-bar]').forEach(e=>e.onclick=()=>{if(!e.dataset.justDragged)openTask(e.dataset.bar)});$$('.milestone[data-milestone]').forEach(e=>e.onclick=()=>{if(!e.dataset.justDragged)openMilestone(e.dataset.milestone)});$$('[data-milestone-label]').forEach(e=>e.onclick=()=>openMilestone(e.dataset.milestoneLabel))
}
function populatePhases(){const o=state.phases.map(p=>`<option value="${p.id}">${p.name}</option>`).join('');$('#taskPhase').innerHTML=o;$('#milestonePhase').innerHTML=o}
function readAdditionalSegments(){return $$('#segmentList .segment-row').map(row=>({id:row.dataset.segmentId,start:row.querySelector('[data-segment-start]').value,end:row.querySelector('[data-segment-end]').value}))}
function renderSegmentEditor(segments=[]){$('#segmentList').innerHTML=segments.map(s=>`<div class="segment-row" data-segment-id="${s.id}"><label>Resume date<input type="date" data-segment-start value="${s.start}" required></label><label>Pause date<input type="date" data-segment-end value="${s.end}" required></label><button type="button" class="segment-remove" title="Remove period">×</button></div>`).join('');$$('.segment-remove').forEach(b=>b.onclick=()=>b.closest('.segment-row').remove())}
function openTask(id,phaseId){populatePhases();const t=allTasks().find(x=>x.id===id),nodes=allNodes(),segments=t?taskSegments(t):[{id:'',start:iso(new Date()),end:iso(add(new Date(),7))}];$('#dialogTitle').textContent=t?'Edit task':'Add task';$('#taskId').value=t?.id||'';$('#taskPrimarySegmentId').value=segments[0].id||'';$('#taskName').value=t?.name||'';$('#taskPhase').value=t?state.phases.find(p=>p.tasks.some(x=>x.id===id)).id:(phaseId||state.phases[0]?.id);$('#taskPredecessor').innerHTML='<option value="">No predecessor</option>'+nodes.filter(x=>x.id!==id).map(x=>`<option value="${x.id}">${x.type}: ${x.name}</option>`).join('');$('#taskPredecessor').value=t?.predecessor||'';const successors=id?successorNames(id):[];$('#taskSuccessors').textContent='Successors: '+(successors.join(', ')||'none');$('#taskStart').value=segments[0].start;$('#taskEnd').value=segments[0].end;renderSegmentEditor(segments.slice(1));$('#taskProgress').value=t?.progress||0;$('#progressOutput').value=(t?.progress||0)+'%';$('#taskOwner').value=t?.owner||'';$('#taskColor').value=t?.color||'blue';$('#deleteTask').style.visibility=t?'visible':'hidden';$('#taskDialog').showModal()}
function openPhase(id){const p=state.phases.find(x=>x.id===id);$('#phaseId').value=p?.id||'';$('#phaseName').value=p?.name||'';$('#phaseDialogTitle').textContent=p?'Edit phase':'Add a phase';$('#phaseSave').textContent=p?'Save phase':'Add phase';$('#deletePhase').style.visibility=p?'visible':'hidden';$('#phaseDialog').showModal()}
function openMilestone(id,phaseId){populatePhases();const m=allMilestones().find(x=>x.id===id),nodes=allNodes();$('#milestoneId').value=m?.id||'';$('#milestoneName').value=m?.name||'';$('#milestoneDate').value=m?.date||iso(new Date());$('#milestonePhase').value=m?state.phases.find(p=>p.milestones.some(x=>x.id===id)).id:(phaseId||state.phases[0]?.id);$('#milestonePredecessor').innerHTML='<option value="">No predecessor</option>'+nodes.filter(x=>x.id!==id).map(x=>`<option value="${x.id}">${x.type}: ${x.name}</option>`).join('');$('#milestonePredecessor').value=m?.predecessor||'';const successors=id?successorNames(id):[];$('#milestoneSuccessors').textContent='Successors: '+(successors.join(', ')||'none');$('#milestoneDialogTitle').textContent=m?'Edit milestone':'Add milestone';$('#deleteMilestone').style.visibility=m?'visible':'hidden';$('#milestoneDialog').showModal()}
$('#taskForm').onsubmit=e=>{e.preventDefault();const id=$('#taskId').value,taskId=id||'t'+Date.now(),predecessor=$('#taskPredecessor').value||'',segments=[{id:$('#taskPrimarySegmentId').value||taskId+'s1',start:$('#taskStart').value,end:$('#taskEnd').value},...readAdditionalSegments()].sort((a,b)=>a.start.localeCompare(b.start));if(segments.some(s=>!s.start||!s.end||s.end<s.start))return toast('Every work period needs valid start and end dates');for(let i=1;i<segments.length;i++)if(segments[i].start<=segments[i-1].end)return toast('Work periods cannot overlap');if(id&&createsCycle(id,predecessor))return toast('That relationship would create a dependency cycle');const obj={id:taskId,name:$('#taskName').value,start:segments[0].start,end:segments[segments.length-1].end,segments,progress:+$('#taskProgress').value,predecessor,owner:($('#taskOwner').value||'—').toUpperCase(),color:$('#taskColor').value};if(id)state.phases.forEach(p=>p.tasks=p.tasks.filter(t=>t.id!==id));state.phases.find(p=>p.id===$('#taskPhase').value).tasks.push(obj);$('#taskDialog').close();render();toast(id?'Task updated':'Task added')};
$('#deleteTask').onclick=()=>{const id=$('#taskId').value;state.phases.forEach(p=>{p.tasks=p.tasks.filter(t=>t.id!==id);p.tasks.forEach(t=>{if(t.predecessor===id)t.predecessor=''})});$('#taskDialog').close();render();toast('Task deleted')};$('#addSegmentBtn').onclick=()=>{const current=readAdditionalSegments(),last=current[current.length-1],base=last?.end||$('#taskEnd').value||iso(new Date()),start=iso(add(parse(base),7));renderSegmentEditor([...current,{id:'s'+Date.now(),start,end:iso(add(parse(start),6))}])};$('#taskProgress').oninput=e=>$('#progressOutput').value=e.target.value+'%';$('#addTaskTop').onclick=()=>openTask();$('#closeDialog').onclick=$('#cancelDialog').onclick=()=>$('#taskDialog').close();
$('#addPhaseBtn').onclick=()=>openPhase();$$('.phase-close').forEach(b=>b.onclick=()=>$('#phaseDialog').close());$('#phaseForm').onsubmit=e=>{e.preventDefault();const id=$('#phaseId').value,p=state.phases.find(x=>x.id===id);if(p)p.name=$('#phaseName').value.toUpperCase();else state.phases.push({id:'p'+Date.now(),name:$('#phaseName').value.toUpperCase(),collapsed:false,tasks:[],milestones:[]});$('#phaseDialog').close();render();toast(id?'Phase updated':'Phase added')};$('#deletePhase').onclick=()=>{const id=$('#phaseId').value,p=state.phases.find(x=>x.id===id);if(p&&(p.tasks.length||p.milestones.length)&&!confirm('Delete this phase and all its contents?'))return;state.phases=state.phases.filter(x=>x.id!==id);$('#phaseDialog').close();render();toast('Phase deleted')};
$$('.milestone-close').forEach(b=>b.onclick=()=>$('#milestoneDialog').close());$('#milestoneForm').onsubmit=e=>{e.preventDefault();const id=$('#milestoneId').value,predecessor=$('#milestonePredecessor').value||'';if(id&&createsCycle(id,predecessor))return toast('That relationship would create a dependency cycle');const obj={id:id||'m'+Date.now(),name:$('#milestoneName').value,date:$('#milestoneDate').value,predecessor};if(id)state.phases.forEach(p=>p.milestones=p.milestones.filter(m=>m.id!==id));state.phases.find(p=>p.id===$('#milestonePhase').value).milestones.push(obj);$('#milestoneDialog').close();render();toast(id?'Milestone updated':'Milestone added')};$('#deleteMilestone').onclick=()=>{const id=$('#milestoneId').value;state.phases.forEach(p=>{p.milestones=p.milestones.filter(m=>m.id!==id);p.tasks.forEach(t=>{if(t.predecessor===id)t.predecessor=''});p.milestones.forEach(m=>{if(m.predecessor===id)m.predecessor=''})});$('#milestoneDialog').close();render();toast('Milestone deleted')};
function renderOffDayList(){const days=state.calendar.offDays;$('#offDayList').innerHTML=days.length?days.map(d=>`<div class="off-day-item"><strong>${parse(d.date).toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'})}</strong><small>${d.label||'Non-working day'}</small><button type="button" data-off-remove="${d.date}">Remove</button></div>`).join(''):'<div class="off-day-empty">No custom off days added.</div>';$$('[data-off-remove]').forEach(b=>b.onclick=()=>{state.calendar.offDays=state.calendar.offDays.filter(d=>d.date!==b.dataset.offRemove);renderOffDayList();render();toast('Off day removed')})}
function openCalendar(){state.calendar=state.calendar||{shadeWeekends:false,offDays:[]};$('#shadeWeekends').checked=!!state.calendar.shadeWeekends;$('#offDayDate').value=iso(new Date());$('#offDayLabel').value='';renderOffDayList();$('#calendarDialog').showModal()}
function setView(view){currentView=view;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$('#timelineView').classList.toggle('hidden',view!=='timeline');$('#boardView').classList.toggle('active',view==='board');$('#listView').classList.toggle('active',view==='list');$('.toolbar-actions').style.visibility=view==='timeline'?'visible':'hidden'}
function slug(){return(state.title||'project').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function chartSvg(){
 const r=range(),px=16,left=210,width=Math.max(900,left+r.total*px),rows=state.phases.reduce((n,p)=>n+1+p.tasks.length+p.milestones.length,0),height=90+rows*38;
 let y=74,body='',positions={},continuations='';const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));
 for(let d=0;d<=r.total;d+=7){const x=left+d*px,dt=add(r.min,d);body+=`<line x1="${x}" y1="52" x2="${x}" y2="${height-20}" stroke="#e8ebef"/><text x="${x+4}" y="45" font-size="9" fill="#738096">${dt.toLocaleDateString('en',{month:'short',day:'numeric'})}</text>`}
 const custom=new Set((state.calendar?.offDays||[]).map(d=>d.date));for(let i=0;i<r.total;i++){const date=add(r.min,i),key=iso(date),isCustom=custom.has(key),weekend=state.calendar?.shadeWeekends&&(date.getDay()===0||date.getDay()===6);if(isCustom||weekend)body+=`<rect x="${left+i*px}" y="52" width="${px}" height="${height-72}" fill="${isCustom?'#dfe3e8':'#eef0f3'}" opacity=".72"/>`}
 state.phases.forEach(p=>{body+=`<rect x="0" y="${y-20}" width="${width}" height="32" fill="#f4f6f8"/><text x="18" y="${y}" font-size="10" font-weight="700" fill="#172033">${esc(p.name)}</text>`;y+=38;p.tasks.forEach(t=>{const segmentPositions=taskSegments(t).map(s=>{const x=left+Math.round((parse(s.start)-r.min)/DAY)*px,w=days(s.start,s.end)*px;return{x,w,right:x+w}}),rowY=y-7;positions[t.id]={left:segmentPositions[0].x,right:segmentPositions[segmentPositions.length-1].right,y:rowY};for(let i=1;i<segmentPositions.length;i++)if(segmentPositions[i].x-segmentPositions[i-1].right>3)continuations+=`<path d="M${segmentPositions[i-1].right} ${rowY} H${segmentPositions[i].x+1}" fill="none" stroke="#9aa4b3" stroke-width="1.1" stroke-dasharray="3 3" marker-end="url(#seg)"/>`;body+=`<text x="18" y="${y}" font-size="10" fill="#445066">${esc(t.name)}</text>`+segmentPositions.map((s,i)=>`<rect x="${s.x}" y="${y-20}" rx="4" width="${s.w}" height="22" fill="${colorValue(t.color)}"/><rect x="${s.x}" y="${y-20}" rx="4" width="${s.w*t.progress/100}" height="22" fill="#172033" opacity=".24"/><text class="task-bar-label" x="${s.x+7}" y="${y-6}" font-size="9" font-weight="700" fill="#111827" style="fill:#111827">${esc(i?'Continued':t.name)}</text>`).join('');y+=38});p.milestones.forEach(m=>{const x=left+Math.round((parse(m.date)-r.min)/DAY)*px;positions[m.id]={left:x-10,right:x+10,y:y-10};body+=`<text x="18" y="${y}" font-size="10" fill="#445066">◆ ${esc(m.name)}</text><rect x="${x-7}" y="${y-17}" width="14" height="14" transform="rotate(45 ${x} ${y-10})" fill="#17233c"/><text x="${x+13}" y="${y-6}" font-size="9" fill="#17233c">${esc(m.name)}</text>`;y+=38})});
 let arrows='';allNodes().forEach(n=>{const a=positions[n.predecessor],b=positions[n.id];if(a&&b)arrows+=`<path d="${dependencyPath(a,b)}" fill="none" stroke="#778399" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round" marker-end="url(#a)"/>`});
 return`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><rect width="100%" height="100%" fill="#fff"/><text x="18" y="27" font-family="Arial" font-size="20" font-weight="700" fill="#172033">${esc(state.title)}</text><defs><style>.task-bar-label{fill:#111827!important}</style><marker id="a" viewBox="0 0 10 10" refX="9.5" refY="5" markerWidth="5.5" markerHeight="5.5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#778399"/></marker><marker id="seg" viewBox="0 0 10 10" refX="9.5" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#9aa4b3"/></marker></defs><g font-family="Arial">${body}${continuations}${arrows}</g></svg>`
}
function exportSvg(){download(new Blob([chartSvg()],{type:'image/svg+xml'}),slug()+'-gantt.svg');toast('SVG exported')}
function exportPng(){const svg=chartSvg(),img=new Image(),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));img.onload=()=>{const c=document.createElement('canvas');c.width=img.width*2;c.height=img.height*2;const ctx=c.getContext('2d');ctx.scale(2,2);ctx.drawImage(img,0,0);c.toBlob(b=>download(b,slug()+'-gantt.png'),'image/png');URL.revokeObjectURL(url);toast('PNG exported')};img.src=url}
function exportJson(){download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),slug()+'-project.json');toast('Project saved')}
function startBlankProject(){const id='p'+Date.now();state={title:'Untitled project',style:state.style||'executive',calendar:{shadeWeekends:false,offDays:[]},phases:[{id,name:'PHASE 1',collapsed:false,tasks:[],milestones:[]}]};zoom='week';$('#overviewTitle').textContent=state.title;$('#newProjectDialog').close();setView('timeline');render();toast('New project ready')}
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('#styleSelect').onchange=e=>{state.style=e.target.value;render();toast(`${e.target.options[e.target.selectedIndex].text} style applied`)};$('#zoomControl').onclick=e=>{if(!e.target.dataset.zoom)return;zoom=e.target.dataset.zoom;$$('#zoomControl button').forEach(b=>b.classList.toggle('active',b===e.target));renderTimeline()};$('#collapseBtn').onclick=()=>{const all=state.phases.every(p=>p.collapsed);state.phases.forEach(p=>p.collapsed=!all);render()};$('#todayBtn').onclick=()=>{const line=$('.today-line');line?$('#timelineWrap').scrollTo({left:Math.max(0,line.offsetLeft-300),behavior:'smooth'}):toast('Today is outside this plan')};$('#editProject').onclick=()=>{const name=prompt('Project name',state.title);if(name){state.title=name;$('#overviewTitle').textContent=name;save()}};
$('#saveBtn').onclick=exportJson;$('#newBtn').onclick=()=>$('#newProjectDialog').showModal();$$('.new-project-close').forEach(b=>b.onclick=()=>$('#newProjectDialog').close());$('#newWithoutSave').onclick=startBlankProject;$('#newSave').onclick=()=>{exportJson();setTimeout(startBlankProject,120)};$('#calendarBtn').onclick=openCalendar;$$('.calendar-close').forEach(b=>b.onclick=()=>$('#calendarDialog').close());$('#shadeWeekends').onchange=e=>{state.calendar.shadeWeekends=e.target.checked;render();toast(e.target.checked?'Weekends shaded':'Weekend shading hidden')};$('#addOffDay').onclick=()=>{const date=$('#offDayDate').value,label=$('#offDayLabel').value.trim();if(!date)return toast('Choose a date');const existing=state.calendar.offDays.find(d=>d.date===date);if(existing)existing.label=label||existing.label;else state.calendar.offDays.push({date,label});state.calendar.offDays.sort((a,b)=>a.date.localeCompare(b.date));renderOffDayList();render();$('#offDayLabel').value='';toast('Off day added')};$('#openBtn').onclick=()=>$('#importFile').click();$('#exportBtn').onclick=()=>$('#exportDialog').showModal();$$('.export-close').forEach(b=>b.onclick=()=>$('#exportDialog').close());$('#exportSvg').onclick=exportSvg;$('#exportPng').onclick=exportPng;$('#exportPdf').onclick=()=>{setView('timeline');$('#exportDialog').close();setTimeout(()=>window.print(),100)};$('#exportJson').onclick=exportJson;$('#importJson').onclick=()=>$('#importFile').click();$('#importFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result);if(!data.phases||!Array.isArray(data.phases))throw Error();state=migrateState(data);$('#overviewTitle').textContent=state.title;$('#exportDialog').close();render();toast('Project opened')}catch{toast('This project file is not valid')}};reader.readAsText(file);e.target.value=''};
$('#overviewTitle').textContent=state.title;render();setView(currentView);
